import PrimaryNavigation from "@/components/client/PrimaryNavigation";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <div className="w-full border-b">
        <div className="mx-auto max-w-screen-2xl px-5">
          <PrimaryNavigation />
        </div>
      </div>

      <div className="py-[2vh]">
        <div className="mx-auto max-w-screen-2xl px-5 ">

          {children}
        </div>
      </div>
    </div>
  );
}
