import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/context/ThemeProvider";
import { Toaster } from "sonner";
import AuthContext from "@/components/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </AuthContext>
        <Toaster />
      </body>
    </html>
  );
}
