// = = = = = = = = = = = = = = = = = = = =
// DASHBOARD LAYOUT
// = = = = = = = = = = = = = = = = = = = =

import NavigationBar from "@/components/admin/NavigationBar";
import PrimaryNavigation from "@/components/client/PrimaryNavigation";
import { authOptions } from "@/helper/authOptions";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);

  if (!session?.user) {
    redirect("/");
  }

  return (
    <div>
      <div className="w-full border-b">
        <div className="mx-auto px-5">
          <PrimaryNavigation />
        </div>
      </div>

      <div className="py-[2vh] grid grid-cols-12 px-5">
        <div className="col-span-3">
          <NavigationBar />
        </div>
        <div className="col-span-9">{children}</div>
      </div>
    </div>
  );
}
